# PromptCrafter 示例配置文件，包含模型名称、参数以及输出设置。
model:
  name: gpt-4.1
  temperature: 0.7
  max_tokens: 512

placeholders:
  - 职业
  - 风格
  - 主题

output:
  directory: output
  filename: result.txt

logging:
  level: INFO
  file: promptcrafter.log
