openai_model: "gpt-4"
temperature: 0.7
params:
  - name: 职业
    prompt: "请生成一个有趣的职业名称"
  - name: 主题
    prompt: "请生成一个未来科技相关的主题"
  - name: 风格
    prompt: "请生成一种语气风格，如轻松、严肃、幽默"
output_file: "output/result.txt"
